pipelines:
  definitions:
    - step: &install_and_test
        name: Install and run tests
        image: node:18.15.0
        caches:
          - node
        script:
          - yarn install
          - yarn run test:ci

    - step: &build_storybook
        name: Build Storybook
        image: node:18.15.0
        caches:
          - node
        artifacts:
          - storybook-static/**
        script:
          - yarn install
          - yarn build-storybook

    - step: &check_pr
        name: Check Pull Request
        script:
          - ./bitbucket-pipelines-check-pr.sh "$BITBUCKET_PR_DESTINATION_BRANCH" "$BITBUCKET_BRANCH" "$BITBUCKET_REPO_FULL_NAME" "$CHATBOT_KEY" "$BITBUCKET_PR_ID" "CH96V73FB"

    - step: &push_github
        name: Push to open source repo
        image: atlassian/default-image:2
        script:
          - git remote add public $PUBLIC_REPO
          - git checkout --orphan open-source-master
          - rm -f .env
          - rm -f .env.local
          - mv -f PUBLIC_README.md README.md
          - git add --all
          - 'git commit -m "master"'
          - git push -f public open-source-master:master

  pull-requests:
    "**":
      - step: *check_pr
      - step: *install_and_test
      - step: *build_storybook
  branches:
    develop:
      - step: *install_and_test
      - step: *build_storybook
    staging:
      - step: *install_and_test
    master:
      - step: *install_and_test
      - step: *push_github
