const COLLECTION_PROJECT_DIRECT_INCOME = "direct-income";
const COLLECTION_PROJECT_INDIRECT_INCOME = "indirect-income";
const COLLECTION_PROJECT_DIRECT_BENEFITS = "direct-benefits";
const COLLECTION_PROJECT_INDIRECT_BENEFITS = "indirect-benefits";
const COLLECTION_PROJECT_DIRECT_CONSERVATION_PAYMENTS = "direct-conservation-payments";
const COLLECTION_PROJECT_INDIRECT_CONSERVATION_PAYMENTS = "indirect-conservation-payments";
const COLLECTION_PROJECT_DIRECT_MARKET_ACCESS = "direct-market-access";
const COLLECTION_PROJECT_INDIRECT_MARKET_ACCESS = "indirect-market-access";
const COLLECTION_PROJECT_DIRECT_CAPACITY = "direct-capacity";
const COLLECTION_PROJECT_INDIRECT_CAPACITY = "indirect-capacity";
const COLLECTION_PROJECT_DIRECT_TRAINING = "direct-training";
const COLLECTION_PROJECT_INDIRECT_TRAINING = "indirect-training";
const COLLECTION_PROJECT_DIRECT_LAND_TITLE = "direct-land-title";
const COLLECTION_PROJECT_INDIRECT_LAND_TITLE = "indirect-land-title";
const COLLECTION_PROJECT_DIRECT_LIVELIHOODS = "direct-livelihoods";
const COLLECTION_PROJECT_INDIRECT_LIVELIHOODS = "indirect-livelihoods";
const COLLECTION_PROJECT_DIRECT_PRODUCTIVITY = "direct-productivity";
const COLLECTION_PROJECT_INDIRECT_PRODUCTIVITY = "indirect-productivity";
export const COLLECTION_PROJECT_DIRECT_OTHER = "direct-other";
const COLLECTION_PROJECT_INDIRECT_OTHER = "indirect-other";

export const PROJECT_RESTORATION_PARTNER_COLLECTIONS = [
  COLLECTION_PROJECT_DIRECT_INCOME,
  COLLECTION_PROJECT_INDIRECT_INCOME,
  COLLECTION_PROJECT_DIRECT_BENEFITS,
  COLLECTION_PROJECT_INDIRECT_BENEFITS,
  COLLECTION_PROJECT_DIRECT_CONSERVATION_PAYMENTS,
  COLLECTION_PROJECT_INDIRECT_CONSERVATION_PAYMENTS,
  COLLECTION_PROJECT_DIRECT_MARKET_ACCESS,
  COLLECTION_PROJECT_INDIRECT_MARKET_ACCESS,
  COLLECTION_PROJECT_DIRECT_CAPACITY,
  COLLECTION_PROJECT_INDIRECT_CAPACITY,
  COLLECTION_PROJECT_DIRECT_TRAINING,
  COLLECTION_PROJECT_INDIRECT_TRAINING,
  COLLECTION_PROJECT_DIRECT_LAND_TITLE,
  COLLECTION_PROJECT_INDIRECT_LAND_TITLE,
  COLLECTION_PROJECT_DIRECT_LIVELIHOODS,
  COLLECTION_PROJECT_INDIRECT_LIVELIHOODS,
  COLLECTION_PROJECT_DIRECT_PRODUCTIVITY,
  COLLECTION_PROJECT_INDIRECT_PRODUCTIVITY,
  COLLECTION_PROJECT_DIRECT_OTHER,
  COLLECTION_PROJECT_INDIRECT_OTHER
];
