import { useT } from "@transifex/react";

const COLLECTION_PROJECT_PAID_NURSERY_OPERATIONS = "paid-nursery-operations";
const COLLECTION_PROJECT_PAID_PROJECT_MANAGEMENT = "paid-project-management";
export const COLLECTION_PROJECT_PAID_OTHER = "paid-other-activities";
const COLLECTION_PROJECT_VOLUNTEER_NURSERY_OPERATIONS = "volunteer-nursery-operations";
const COLLECTION_PROJECT_VOLUNTEER_PROJECT_MANAGEMENT = "volunteer-project-management";
const COLLECTION_PROJECT_VOLUNTEER_OTHER = "volunteer-other-activities";

const COLLECTION_SITE_PAID_SITE_ESTABLISHMENT = "paid-site-establishment";
const COLLECTION_SITE_PAID_PLANTING = "paid-planting";
const COLLECTION_SITE_PAID_SITE_MAINTENANCE = "paid-site-maintenance";
const COLLECTION_SITE_PAID_SITE_MONITORING = "paid-site-monitoring";
export const COLLECTION_SITE_PAID_OTHER = "paid-other-activities";
const COLLECTION_SITE_VOLUNTEER_SITE_ESTABLISHMENT = "volunteer-site-establishment";
const COLLECTION_SITE_VOLUNTEER_PLANTING = "volunteer-planting";
const COLLECTION_SITE_VOLUNTEER_SITE_MAINTENANCE = "volunteer-site-maintenance";
const COLLECTION_SITE_VOLUNTEER_SITE_MONITORING = "volunteer-site-monitoring";
const COLLECTION_SITE_VOLUNTEER_OTHER = "volunteer-other-activities";

export const PROJECT_WORKDAY_COLLECTIONS = [
  COLLECTION_PROJECT_PAID_PROJECT_MANAGEMENT,
  COLLECTION_PROJECT_VOLUNTEER_PROJECT_MANAGEMENT,
  COLLECTION_PROJECT_PAID_NURSERY_OPERATIONS,
  COLLECTION_PROJECT_VOLUNTEER_NURSERY_OPERATIONS,
  COLLECTION_PROJECT_PAID_OTHER,
  COLLECTION_PROJECT_VOLUNTEER_OTHER
];

export const SITE_WORKDAY_COLLECTIONS = [
  COLLECTION_SITE_PAID_SITE_ESTABLISHMENT,
  COLLECTION_SITE_VOLUNTEER_SITE_ESTABLISHMENT,
  COLLECTION_SITE_PAID_PLANTING,
  COLLECTION_SITE_VOLUNTEER_PLANTING,
  COLLECTION_SITE_PAID_SITE_MAINTENANCE,
  COLLECTION_SITE_VOLUNTEER_SITE_MAINTENANCE,
  COLLECTION_SITE_PAID_SITE_MONITORING,
  COLLECTION_SITE_VOLUNTEER_SITE_MONITORING,
  COLLECTION_SITE_PAID_OTHER,
  COLLECTION_SITE_VOLUNTEER_OTHER
];

export const getReadableWorkdayCollectionName = (collection: string, t: typeof useT = (t: string) => t) => {
  const value = {
    [COLLECTION_PROJECT_PAID_NURSERY_OPERATIONS]: t("Nursery Operations - Paid Workday"),
    [COLLECTION_PROJECT_PAID_PROJECT_MANAGEMENT]: t("Project Management - Paid Workday"),
    [COLLECTION_PROJECT_PAID_OTHER]: t("Other Activities - Paid Workday"),
    [COLLECTION_PROJECT_VOLUNTEER_NURSERY_OPERATIONS]: t("Nursery Operations  - Volunteer"),
    [COLLECTION_PROJECT_VOLUNTEER_PROJECT_MANAGEMENT]: t("Project Management - Volunteer"),
    [COLLECTION_PROJECT_VOLUNTEER_OTHER]: t("Other Activities - Volunteer"),
    [COLLECTION_SITE_PAID_SITE_ESTABLISHMENT]: t("Site Establishment - Paid Workday"),
    [COLLECTION_SITE_PAID_PLANTING]: t("Planting - Paid Workday"),
    [COLLECTION_SITE_PAID_SITE_MAINTENANCE]: t("Site Maintenance - Paid Workday"),
    [COLLECTION_SITE_PAID_SITE_MONITORING]: t("Site Monitoring - Paid Workday"),
    [COLLECTION_SITE_VOLUNTEER_SITE_ESTABLISHMENT]: t("Site Establishment - Volunteer"),
    [COLLECTION_SITE_VOLUNTEER_PLANTING]: t("Planting - Volunteer"),
    [COLLECTION_SITE_VOLUNTEER_SITE_MAINTENANCE]: t("Site Maintenance - Volunteer"),
    [COLLECTION_SITE_VOLUNTEER_SITE_MONITORING]: t("Site Monitoring - Volunteer")
  };

  return value[collection as keyof typeof value];
};
