export default {
  text: 'text',
  password: 'password',
  number: 'number',
  newPassword: 'newPassword',
  textarea: 'textarea',
  tel: 'tel',
  email: 'email',
  radio: 'radio',
  radioGroup: 'radioGroup',
  checkbox: 'checkbox',
  checkboxGroup: 'checkboxGroup',
  toggle: 'toggle',
  asyncSelect: 'asyncSelect',
  select: 'select',
  file: 'file',
  multiUpload: 'multiUpload',
  seperator: 'seperator',
  map: 'map',
  fileTypes: {
    image: 'image/png, image/jpeg, image/gif',
    imagePdf: 'application/pdf, image/png, image/jpeg, image/gif',
    video: 'video/mp4, video/quicktime'
  },
  multiText: 'multiText',
  userSelect: 'userSelect',
  url: 'url',
  date: 'date',
  externalLink: 'externalLink',
  textDescription: 'textDescription',
  button: 'button',
  videoPreview: 'videoPreview'
};
