export const ModalId = {
  ADD_POLYGON: "addPolygon",
  ADD_POLYGONS: "addPolygons",
  APPLICATION_CLOSED: "ApplicationClosed",
  APPROVE_POLYGONS: "ApprovePolygons",
  CHANGE_REQUEST: "Change Request",
  CHANGE_REQUEST_STATUS: "ChangeRequestStatus",
  CONFIRMATION: "Confirmation",
  CONFIRM_EDIT: "ConfirmEdit",
  CONFIRM_SITES_STATUS_CHANGE: "ConfirmSiteStatusChange",
  CONFIRM_SITE_DELETION: "ConfirmSiteDeletion",
  CONFIRM_USER: "ConfirmUser",
  CONFIRM_PROJECT_DRAFT_DELETION: "ConfirmProjectDraftDeletion",
  CONFIRM_DELETE: "confirmDelete",
  CONFIRM_UPDATE: "ConfirmUpdate",
  CONFIRM_NURSERY_DELETION: "ConfirmNurseryDeletion",
  CONFIRM_POLYGON_DELETION: "ConfirmPolygonDeletion",
  CONFIRMATION_MODAL: "ConfirmationModal",
  CONFIRM_POLYGON_APPROVAL: "confirmPolygonApproval",
  CONFIRM_POLYGON_SUBMISSION: "confirmPolygonApprovalSubmission",
  DELETE_POLYGON: "deletePolygon",
  PITCH_DELETE_MODAL: "PitchDeleteModal",
  DELETE_IMAGE: "DeleteImage",
  DELETE_DRAFT: "DeleteDraft",
  ERROR_MODAL: "ErrorModal",
  FORM_MODAL: "FormModal",
  INVITE_MONITORING_PSRTNER_MODAL: "InviteMonitoringPartnerModal",
  MONITORING_PARTNER: "MonitoringPartner",
  MODAL_CONFIRM: "ModalConfirm",
  MODAL_CONFIRM_DELETE_PARTNER: "ModalConfirmDeletePartner",
  MODAL_WITH_LOGO: "ModalWithLogo",
  ORGANIZATION_EDIT_MODAL: "OrganizationEditModal",
  PITCH_EDIT_MODAL: "pitchEditModal",
  REVIEW_IN_PROGRESS: "ReviewinProgress",
  UPLOAD_IMAGES: "UploadImages",
  STATUS: "Status",
  STATUS_CHANGE: "StatusChange",
  SUBMIT_POLYGONS: "Submit Polygons",
  SAVE_AND_CLOSE_MODAL: "SaveAndCloseModal",
  IMAGE_GALLERY_PREVIEWER: "ImageGalleryPreviewer",
  SHAPE_PROPERTIES_MODAL: "ShapePropertiesModal",
  WELCOME_MODAL: "WelcomeModal",
  WARNING: "Warning"
};
